"""empty message

Revision ID: 7102e8bb2735
Revises: d8ca9820d936
Create Date: 2019-09-14 00:59:32.805724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7102e8bb2735'
down_revision = 'd8ca9820d936'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'profiles', ['profile_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'profile_id')
    # ### end Alembic commands ###
